name: build

env:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    
on:
  push:
    branches: [ main, develop, master, feature/* ]
  pull_request:
    branches: [ main, develop, master ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run:
        dotnet restore
    - name: Build
      run: dotnet build --no-restore -nologo
    - name: Test
      run: dotnet test --no-build --verbosity normal
